### ISSUE TITLE
inherit.aes .group

### ISSUE THREAD

**Issue by jsta** [mjskay/tidybayes#100]
When I try to re-build the README I get a lot of errors like:

> Error in FUN(X[[i]], ...) : object '.group' not found

and 

> geom_path: Each group consists of only one observation. Do you need to adjust the group
aesthetic?

I managed to "fix" there errors with liberal use of `inherit.aes = FALSE` following https://stackoverflow.com/a/40391432/3362993

I believe I am using the latest versions of `ggplot2` (2.2.1.9000) and `tidybayes` (0.12.0.000002). Would you be interested in a PR for this?

**Comment by jsta** [comment]
See de1dd67033497264a10add5371d4dce635b71bae

**Comment by mjskay** [comment]
This seems to be related to tidyverse/ggplot2#2378 and tidyverse/ggplot2#2351 --- grouped data frames now implicitly create a `.group` variable in ggplot.

I'll be curious to see what happens with tidyverse/ggplot2#2378. In the short term, I think I'd prefer the workaround used in tidyverse/ggplot2#2378 (passing through ungroup() before ggplot()) instead of setting `inherit.aes`, since the group information is not needed in any part of the ggplot spec so it is safe to just chuck it before the spec. 

If you wanted to put in a PR for this I'd love that. If you do, please file it against the `dev` branch. Thanks!

**Comment by mjskay** [comment]
This has been fixed on the ggplot side: using tibble groups in the group aesthetic now uses an opt-in syntax. See tidyverse/ggplot2#2378 and tidyverse/ggplot2@0b4567abda1bc852c31ea5a6362e2fd9def6a890
