### ISSUE TITLE
Multiple stat_lineribbon calls on same plot but differently colored

### ISSUE THREAD

**Issue by jsta** [mjskay/tidybayes#103]
I am trying to plot the output of multiple `stat_lineribbon` calls on the same plot but have them differently colored. I think this is difficult because `ggplot2` only allows for a single `scale_fill_*` per plot. Is there a simpler way to achieve this apart from the following code?

```
library(ggplot2)
library(dplyr)
library(tidybayes)
library(grid)
library(gtable)

dt_1 <- data_frame(x = 1:10) %>%
        group_by_all() %>%
        do(data_frame(y = rnorm(100, .$x) + 1.5)) %>%
        ungroup()

dt_2 <- data_frame(x = 1:10) %>%
  group_by_all() %>%
  do(data_frame(y = rnorm(100, .$x) - 1.5)) %>%
  ungroup()

gg_1 <- ggplot() + 
          stat_summary(data = dt_1, geom = "ribbon", 
             aes(x = x, y = y, fill = forcats::fct_rev(ordered(...prob..))), 
             fun.data = median_qi, fun.args = list(.prob = 0.95), alpha = 0.5) +
          stat_summary(data = dt_1, aes(x = x, y = y), fun.y = median, 
                       geom = "line", color = viridis::viridis(1, begin = 1), 
                       size = 1.25) +
          scale_fill_viridis_d(begin = 1) + 
          theme(legend.position = "none") + ylim(-2, 12)

gg_2 <- ggplot() +
  stat_summary(data = dt_2, geom = "ribbon", 
               aes(x = x, y = y, fill = forcats::fct_rev(ordered(...prob..))), 
               fun.data = median_qi, fun.args = list(.prob = c(0.95)), alpha = 0.5) + 
  stat_summary(data = dt_2, aes(x = x, y = y), fun.y = median, 
               geom = "line", color = viridis::viridis(1, begin = 0.5), 
               size = 1.25) +
  scale_fill_viridis_d(begin = 0.5) + 
  theme_classic() + 
  theme(panel.background = element_rect(fill = "transparent"), 
        plot.background = element_rect(
          color = "transparent", 
          fill = "transparent"), 
        panel.border = element_blank()) + ylim(-2, 12)


g1 <- ggplotGrob(gg_1)
g2 <- ggplotGrob(gg_2)
g2 <- gtable_filter(g2, "panel")

gg <- gtable_add_grob(g1, g2, t = 6, l = 4)

grid.draw(gg)
```

![rplot](https://user-images.githubusercontent.com/7844578/37831780-0ac3817a-2e7d-11e8-8fb7-da1aaeef80a6.png)

**Comment by mjskay** [comment]
If you only want one interval per group, you can use the `fill` and `color` aesthetics simultaneously. Something like this should work:

```r
dt_1 <- 
  data_frame(x = 1:10) %>%
  group_by_all() %>%
  do(data_frame(
    y = rnorm(100, .$x) + 1.5,
    dataset = "a"
  )) %>%
  ungroup()

dt_2 <- data_frame(x = 1:10) %>%
  group_by_all() %>%
  do(data_frame(
    y = rnorm(100, .$x) - 1.5,
    dataset = "b"
  )) %>%
  ungroup()
```

```r
bind_rows(dt_1, dt_2) %>%
  ggplot(aes(x = x, y = y, color = dataset, fill = dataset)) +
  stat_lineribbon(.prob = .95, alpha = 1/2) 
```

![image](https://user-images.githubusercontent.com/6345019/37838921-8f3df662-2e8f-11e8-8ede-450473ab67e2.png)

If you want multiple probability levels per group, the current way `stat_lineribbon` is implemented would require you to adjust the group aesthetic to combine the pre-computed group (which is based on `color`/`fill`) with the probability level, because you are overriding the `fill` aesthetic. Something like this:

```r
bind_rows(dt_1, dt_2) %>%
  ggplot(aes(x = x, y = y, color = dataset, fill = dataset)) +
  stat_lineribbon(aes(group = paste(group, ...prob..)), .prob = c(.5, .8, .95), alpha = 1/4) 
```

![image](https://user-images.githubusercontent.com/6345019/37839628-49611faa-2e91-11e8-8484-284fdeb0ffe0.png)

I've set alpha to be `1/(number of probability levels + 1)` in both cases.

Thanks for raising this --- probably lineribbon should be adjusting the groups correctly to handle this case so you don't have to do it yourself.

Incidentally, it occurred to me from your question that you could get a little silly with this to hack together a gradient plot sort of thing:

```{r}
levels = 10
max_sigma = 2.5

bind_rows(dt_1, dt_2) %>%
  ggplot(aes(x = x, y = y, color = dataset, fill = dataset)) +
  stat_lineribbon(
    aes(group = paste(group, ...prob..)),
    .prob = 1 - pnorm(-seq(max_sigma/levels, max_sigma, length.out = levels))*2,
    alpha = 1/(levels + 1)) +
  scale_alpha_continuous(range = c(0,1))
```

![image](https://user-images.githubusercontent.com/6345019/37839751-a003cbaa-2e91-11e8-86ae-71ce87d9132e.png)

**Comment by mjskay** [comment]
Also this is probably a better gradient approximation:

```r
levels = 30

bind_rows(dt_1, dt_2) %>%
  ggplot(aes(x = x, y = y, color = dataset, fill = dataset)) +
  stat_lineribbon(aes(group = paste(group, ...prob..)), .prob = ppoints(levels), alpha = 1/levels)
```

![image](https://user-images.githubusercontent.com/6345019/37848470-a67ba070-2eaa-11e8-857b-baf507923bb4.png)

(though honestly gradients are pretty bad perceptually so I probably wouldn't use this... :) )

**Comment by mjskay** [comment]
Todos from this:

- [ ] make multiple interval version work without manual adjustment of group aesthetic (this will needs tests to make sure other stuff doesn't break) 
- [ ] add an example of this to vignettes and function docs 
- [ ] possibly have `alpha` only apply to the ribbon for greater clarity

**Comment by mjskay** [comment]
Update: this should work now without needing to specify the `group` aesthetic.

In some cases you might still need to; e.g. if redefining the group to be something else, you'll need to include `stat(.width)` in the definition of group (`.width` is the new name for `...prob..`: `.prob` got renamed to `.width` per #113 and `stat` is the ggplot 3 way to refer to calculated aesthetics).

I'm leaving this open because there are probably some refinements to the approach to this to think about.

**Comment by mjskay** [comment]
This seems well solved at this point. The last remaining bits might be more specific alpha aesthetics, which are dealt with in #193
