### ISSUE TITLE
bayesplot ideas

### ISSUE THREAD

**Issue by jgabry** [mjskay/tidybayes#105]
Hey @mjskay thanks for already doing a bunch to make tidybayes play nice with bayesplot! I’d like to return the favor, so to speak, and ask if there’s anything sensible we can do in bayesplot to make it easier for users of your package (or you as the developer)? For example, maybe being more flexible about how a data frame needs to be structured for MCMC plots? Also allowing data frames to be used for PPC plots? We’re open to suggestions!

One last thing: the vignettes are really great but can I nitpick? It’s not true anymore that bayesplot returns only the ggplot object. We now have a bunch of functions that return the underlying data as as a tidy data frame (thanks to @tjmahr !).

**Comment by jgabry** [comment]
And this really applies to any of the R packages from the Stan team, not just bayesplot (e.g., rstan, rstanarm,  now brms too).

(And we’re going to change the  annoying theme switch bayesplot does by default. I gave into pressure and did it —it wasn’t originally that way— but definitely a mistake in hindsight.)

**Comment by mjskay** [comment]
Thanks for reaching out, it would be great to think about out how tidybayes and bayesplot / the rest of the stan ecosystem can integrate better! 

Its the end of the semester, and I have grading and a conference that will kill my time until the beginning of May---I'll provide some quick thoughts here, but I might not be responsive on this thread until ~May 1. Don't take that as a signal about interest, I think this is a great idea!

> For example, maybe being more flexible about how a data frame needs to be structured for MCMC plots? Also allowing data frames to be used for PPC plots? We’re open to suggestions!

I agree, data frame formats are probably the best way to improve interoperability. Some thoughts:

- One unfortunate bit is that tidybayes uses `.chain` and `.iteration` and bayesplot uses `Chain` and `Iteration` as its naming scheme for tidy formats. In defense of `.chain` and `.iteration`, I chose that naming scheme after how some other packages (like broom) name generated columns, and due to the fact that it guarantees no name collisions with Stan/JAGS variables (since those can't have dots).

- The "scorched earth" approach (in terms of backwards compatibility) would be to unify that naming scheme. Probably this would be tidybayes unifying to bayesplot, although again I have mixed feelings about this in terms of backwards compatibility (let me ruminate on that).

- A softer approach might be an argument in tidybayes functions to output data frames in bayesplot-style and vice versa. E.g. `format = "tidybayes"` or `format = "bayesplot"`, except better names. For that, a consistent name for that argument and its two possible values used by functions in both packages would be ideal. 

- Another (heavier-weight) approach might be a data frame format for tidy samples that explicitly identifies which column has the chain and iteration information. E.g. a subclass of data.frame (or tbl_df) for tidy data frames of samples with a bit of meta-data on it (maybe as some attributes).

- In the lower-hanging fruit column, currently `tidybayes::unspread_samples/ungather_samples` has a `drop_indices` option to drop the `.chain` and `.iteration` columns so that bayesplot functions can work with the output data frame (see the examples [here](http://mjskay.github.io/tidybayes/reference/unspread_samples.html)). It might be nice if that were not necessary when piping into bayesplot functions---e.g. if they either ignored `.chain` and `.iteration` columns or used them if appropriate.

> One last thing: the vignettes are really great but can I nitpick? It’s not true anymore that bayesplot returns only the ggplot object. We now have a bunch of functions that return the underlying data as as a tidy data frame (thanks to @tjmahr !).

Yes, please do nitpick! I've certainly been nitpicky from my side (e.g. on the theme thing), which I hope was not taken as anything more than constructive criticism. I will update the vignettes :)

**Comment by tjmahr** [comment]
I think it would help to unify the naming conventions.

> One unfortunate bit is that tidybayes uses .chain and .iteration and bayesplot uses Chain and Iteration as its naming scheme for tidy formats. In defense of .chain and .iteration, I chose that naming scheme after how some other packages (like broom) name generated columns, and due to the fact that it guarantees no name collisions with Stan/JAGS variables (since those can't have dots).

I follow the dot-name convention myself in other packages I write, like my private, increasingly irrelevant [mcmc-tidying one](https://github.com/tjmahr/tristan). I prefer names like `.chain` because they quickly highlight metadata columns. 

> A softer approach might be an argument in tidybayes functions to output data frames in bayesplot-style and vice versa. E.g. format = "tidybayes" or format = "bayesplot", except better names. For that, a consistent name for that argument and its two possible values used by functions in both packages would be ideal.

Not a fan of using an argument. I would prefer a breaking change to bayesplot or a helper function to drop in the pipelines (`use_bayesplot_names()`).

**Comment by jgabry** [comment]
@mjskay thanks for your initial thoughts. We can definitely pick up this conversation after the busy period. 

Like TJ, I’m open to changing to the dot-name convention in bayesplot. I wouldn’t want to break bayesplot, but we could start allowing the dot-names and also start throwing deprecation warnings if the old names are used. Then eventually we can stop supporting the old ones at all. 

I’ll think about the other stuff and then we can talk more after the semester.

**Comment by jgabry** [comment]
Thanks for the further thoughts.
It’s been a busy week for me and this coming one will be too, but I do have thoughts on this so I will get back to you as soon as I have time to formulate them clearly!

**Comment by jgabry** [comment]
I’ve been thinking more about bayesplot and the rest of the stan ecosystem in relation to tidybayes. I think it could help a lot to have an actual conversation at this point, so maybe a google hangout? @mjskay @tjmahr @paul-buerkner would you be up for that? If so I can coordinate this and set it up.

**Comment by paul-buerkner** [comment]
I am in.

**Comment by mjskay** [comment]
Definitely, sounds good to me! I'm on vacation from June 1-6, so it would have to be after that.

**Comment by paul-buerkner** [comment]
I am on the road on both of these days. Do we have another option?

**Comment by jgabry** [comment]
I’m flexible in June. What would work for you?

**Comment by mjskay** [comment]
I'm traveling on and off in June. The most flexible days in June for me are:

June 12 - any time except 12pm-1pm Eastern
June 18 and 19 - any time

Other days have open spots here and there, but at that point it might be easier to use Doodle or something like that to find a time that works for all of us.

**Comment by paul-buerkner** [comment]
June 18 or 19 would be perfect for me.

**Comment by jgabry** [comment]
Ok let’s say Monday June 18th, 12pm (eastern US time). That seems to work for the three of us, although we haven’t heard from TJ yet. @tjmahr Can you do a google hangout at that time? If so I’ll set up the hangout and send event invitations. If not I’ll set up a doodle so we can find another time more easily.

**Comment by tjmahr** [comment]
I can only do Tuesdays.

**Comment by jgabry** [comment]
Ok, I believe that means we can all do Tuesday June 19th. I’ll send a google hangouts invitation.

**Comment by tjmahr** [comment]
Some notes (1) 

Dot conventions are good for bayesplot.

- We will need to update the data-processing internals of bayesplot when the model is in a dataframe. Like check for Chain/chain/.chain and map to .chain.
- Matrices/arrays should not have this problem
- If there is no chain in the dataframe, add a .chain with NAs.

**Comment by tjmahr** [comment]
Some notes (2)

Some talk about defining scope of packages...

- tidying from tidybayes
- canned plotting recipes in bayesplot
- maybe geoms from tidybayes in their own package?

Goal among our group would be to minimize re-implementing the same tasks in different packages (when the overlapping tasks could make useful functions to export).

**Comment by tjmahr** [comment]
Some notes (3)

We are the new wave of bayesian packages and it would be good to set consistent conventions for naming things for bayesplot/brms/rstanarm/tidybayes. Like hashing out the meaning of words/functions like "fitted" or "predicted".

**Comment by tjmahr** [comment]
Some notes (4)

When we talk about naming conventions, this is a large scope. Names can be:

* Output columns
* Function names
* Parameter names

**Comment by tjmahr** [comment]
Discussion on naming will take place on the Stan discourse. Thread TBD

**Comment by mjskay** [comment]
Thanks for the fun discussion today! (and also for the notes @tjmahr).

Discourse thread on output names is here: http://discourse.mc-stan.org/t/unifying-names-of-output-columns-in-bayesplot-tidybayes-etc/4577

**Comment by mjskay** [comment]
As the release of {posterior} looms I have been cleaning out old issues on {tidybayes} and {ggdist} and came across this. Is there anything else useful to chat about re: bayesplot and the like? @jgabry @tjmahr?

I am gonna close this for now but please comment/reopen if something comes up :). FWIW the next release of ggdist is already ready to go for after posterior hits CRAN, and it will substantially reduce its dependencies in the hope that it is more useful for package authors to build upon.
