### ISSUE TITLE
Make sure additional meta-data (e.g. divergent transitions) can be extracted with tidy_draws, spread_draws, gather_draws

### ISSUE THREAD

**Issue by brockk** [mjskay/tidybayes#109]
Hi @mjskay. Absolutely love tidybayes, I use it practically every day now. 

Have you thought about adding a way to identify divergent transitions? Perhaps as an optional column `.divergent` in the tibble returned in spread_samples / gather_samples?

I am motivated to ask from reading Michael Betancourt's article on biased inference and divergences:
http://mc-stan.org/users/documentation/case-studies/divergences_and_bias.html

Specifically his scatter plots of var1 vs var2 with the divergent transitions in bright green could be something like:

tibble %>% 
  ggplot(aes(x = var1, y = var2, col = .divergent)) + 
  geom_point()

He gets binary indicators for divergent transitions from rtan::get_sampler_params(model).

I can see that you are busy so happy to help (if I can).

Kristian

**Comment by mjskay** [comment]
Oh, that's an interesting idea! I would be open to considering this. I'm not sure I want to make it something that shows up *by default* in the output of `gather_samples` and `spread_samples` just because there are a bunch of possibilities (treedepth, divergences, etc) and because it is not something that would be consistent across different samplers (e.g. Stan vs JAGS or what have you).

That said, maybe one path to this is to add these columns to the output of `as_sample_tibble.stanfit`. That would mean you could pull those columns out explicitly in `spread_samples`/`gather_samples` as if they were parameters. Something like this:

```r
m %>%
  spread_samples(var1, var2, .divergent) %>%
  ggplot(aes(x = var1, y = var2, color = .divergent) +
  geom_point()
```

Thoughts?

(also I am definitely open to pull requests on this if you want to take it on :)).

**Comment by mjskay** [comment]
Awesome! Please file it against the `dev` branch.

**Comment by mjskay** [comment]
This should work now by using the variable name `divergent__` in `spread_draws` or `gather_draws`, or by using `tidy_draws` (which will now include several diagnostic variables). You can see a list of diagnostic variables available (including `divergent__`, `treedepth__`, etc) for a model `m` by running `get_variables(m)` (the variables ending in `__` are diagnostic variables).

**Comment by mjskay** [comment]
I should add: it will work as long as you install the development version from the `dev` branch.

**Comment by brockk** [comment]
I am dying to check this out @mjskay, well done for adding it. Sorry I contributed no code in the end; I have been swamped trying to finish off my thesis. Thanks! Kristian

**Comment by mjskay** [comment]
No worries, I totally understand. :-)
