### ISSUE TITLE
stat_lineribbon introduces non-linear artifacts when using axis limits

### ISSUE THREAD

**Issue by corriebar** [mjskay/tidybayes#169]
`stat_lineribbon` introduces non-linear artifacts (for linear models) when zooming in on certain parts of the plot:
```{r}
tibble(x = 1:10) %>%
  group_by_all() %>%
  do(tibble(y = rnorm(100, .$x))) %>%
  ggplot(aes(x = x, y = y)) +
  stat_lineribbon() +
  scale_fill_brewer() +
  ylim(0, 8)
```
![image](https://user-images.githubusercontent.com/11877945/57687990-bba85f80-763c-11e9-833a-e6c670a117b3.png)

For `geom_lineribbon` some of the outer ribbons are lost in the plot, which makes it more obvious that the plot is faulty:
```{r}
tibble(x = 1:10) %>%
  group_by_all() %>%
  do(tibble(y = rnorm(100, .$x))) %>%
  median_qi(.width = c(.5, .8, .95)) %>%
  ggplot(aes(x = x, y = y)) +
  geom_lineribbon() +
  scale_fill_brewer() +
  ylim(0, 8)
```
![image](https://user-images.githubusercontent.com/11877945/57688130-ff9b6480-763c-11e9-8aa6-16c2587a435e.png)

**Comment by mjskay** [comment]
I think this is a general issue with using `ylim()` to limit axes / to zoom in, not an issue with lineribbon: `ylim` removes data outside of its bounds instead of drawing the plot and clipping it, which leads to weird behavior for most geoms. 

If you replace `ylim(0, 8)` with `coord_cartesian(ylim = c(0, 8))` do you get the expected behavior?

See also this stackoverflow post: https://stackoverflow.com/questions/25685185/limit-ggplot2-axes-without-removing-data-outside-limits-zoom

**Comment by corriebar** [comment]
Yes, you're right, `coord_cartesian(ylim=c(0,8))` works as expected.

**Comment by mjskay** [comment]
Great!
