### ISSUE TITLE
halfeye free y  scale with multiple variables

### ISSUE THREAD

**Issue by fkgruber** [mjskay/tidybayes#208]
When plotting multiple halfeye plots for different variables the y scale seems to be the same for each of the variable and this leads to very flat distributions in some cases. is it possible to make the density plots independent of the other variables?
For example, in the plot for the last 3 variables there is a second mode as shown by the credible interval but it can't be seen by the density plot because of the scaling.
![image](https://user-images.githubusercontent.com/4311763/66347377-2fb40e80-e922-11e9-86c1-b9c6c8689b12.png)

Thanks
FKG

**Comment by fkgruber** [comment]
just to be extra clear I'm thinking of an option as in facet_wrap where you can do scales='free' vs scales='fixed_y'

for fixed:
ggplot(aes(x=HR,fill=Experiment))+geom_density()+facet_wrap(~Experiment,scales='fixed',ncol=1)

![image](https://user-images.githubusercontent.com/4311763/66348355-5a06cb80-e924-11e9-86fb-1a604886a23d.png)


for free:
ggplot(aes(x=HR,fill=Experiment))+geom_density()+facet_wrap(~Experiment,scales='free_y',ncol=1)
![image](https://user-images.githubusercontent.com/4311763/66348452-9803ef80-e924-11e9-8215-8eeb51b0a6eb.png)
png)

**Comment by mjskay** [comment]
Yes --- in the dev version of tidybayes (i.e. if you install from github instead of from CRAN) you should be able to get the behavior you want with something like `stat_halfeyeh(normalize = "height")`.

**However**, I am very likely to change the option names for that argument, as they are pretty opaque currently. In the next version this will likely be something like `stat_halfeyeh(normalize = "group")`. You can track issue #197 for those changes.

**Comment by fkgruber** [comment]
thanks. that works

**Comment by mjskay** [comment]
Great!
