### ISSUE TITLE
Extracting pre-warmup samples from Stan model

### ISSUE THREAD

**Issue by mark-andrews** [mjskay/tidybayes#236]
Using `rstan::extract` with `permuted=F` and `inc_warmup=T`, I can extract all samples including pre-warmup samples into an array. It appears to me that `tidybayes::tidy_draws`, `tidybayes::spread_draws`,   `tidybayes::gather_draws`,  etc., all provide only post-warmup samples. I understand that is what would be desired in almost all cases. However, am I right in thinking that it is not possible to get the pre-warmup samples using these functions?

**Comment by mjskay** [comment]
Yes, currently it is not possible. However, having an option for this wouldn't be a bad idea, let me see what I can do (probably not until this summer)

**Comment by jfsalzmann** [comment]
Has there been any progress on this, or are there workarounds available? @mjskay

**Comment by mjskay** [comment]
Uh yes actually! Because the draws formats from {posterior} have been integrated into the stan packages and are supported in {tidybayes}, this is a lot easier now. 

If you're using {rstan} something like this should work:

```r
m |>
  extract(permuted = FALSE, inc_warmup = TRUE) |> 
  posterior::as_draws_df() |>
  spread_draws(...)  # etc
```

and if you're using {cmdstanr}, something like this:

```r
m$draws(format = "df", inc_warmup = TRUE) |>
  spread_draws(...)  # etc
```

Lemme know if that helps!

**Comment by jfsalzmann** [comment]
amazing, thanks!
