### ISSUE TITLE
Add function for generating nested indices

### ISSUE THREAD

**Issue by aornugent** [mjskay/tidybayes#58]
Hia, love the package.

Do you have a system for indexing hierarchical data? I often do something like:

```{r}
#` Indexing nested factors
nestd <- function(x, y){
  nestbl <- table(factor(x), factor(y))
  idx <- apply(nestbl, 1, function(x) which(x > 0))
  return(idx)
}

df <- data.frame(plot = rep(1:10, times = 2), site = rep(1:5, each = 2, times = 2))
id <- nestd(df$plot, df$site)
```

And in the model:

```{stan}
model {
  for(i in 1:n_plot){
     mu_plot[i] ~ dnorm(mu_site[site[i]], tau_plot);
  }
  for(j in 1:n_site){
    mu_site[j] ~ dnorm(mu_overall, tau_site);
  }
  mu_overall ~ dnorm(0, 100);
  tau_plot ~ cauchy(0, 5);
  tau_site ~ cauchy(0, 5);
}
```

**Comment by mjskay** [comment]
Interesting question! Could you clarify a few things that would help me answer?

- Is the question if there are functions in tidybayes for generating a variable like `id`? If I'm reading correctly, `id` is a vector such that `id[p]` is the value of `site` for plot `p`.

- `id` is not used in your model presently, but I was wondering if this line:

    ```
         mu_plot[i] ~ dnorm(mu_site[site[i]], tau_plot);
    ```

    Was intended to be something like:

    ```
         mu_plot[i] ~ dnorm(mu_site[id[i]], tau_plot);
    ```

    Both work given the current value of `df`, but I think the former might break if the order of the rows in `df` changes, where the latter would not.

- Is there intended to be a portion of the model for the observations? E.g. if `df` had a `y` column, and the model contained something like:

    ```
    for (k in 1:n) {
        y[k] ~ dnorm(mu_plot[plot[k]], sigma);
    }
    ```

- So I can be sure we are on the same page, is there a particular modeling language you are writing this in? It looks not-quite-JAGS/BUGS-ish (due to `cauchy`) and not-quite-Stan-ish (due to `dnorm`), so I want to be sure I'm understanding correctly before I try to answer.

**Comment by aornugent** [comment]
Correct on all counts! Apologies that it wasn't clear, it was a rushed sketch of a minimal example.

- `id[i] == site[i]`, which is of length `n_plot` indexing plots within sites. As you have intuited, the correct model code should be `mu_plot[i] ~ dnorm(mu_site[id[i]], tau_plot);`. Alternatively, `id` could be renamed `site_id`.
- I left off the observation model for brevity, but `y[k] ~ dnorm(mu_plot[plot[k]], sigma);` is exactly right.
- The language mish-mash is clearly a symptom of porting said models from JAGS to Stan as we speak. We can work in Stan so `dnorm(0, 100)` should be `normal(0, 100)` etc.

**Comment by mjskay** [comment]
Thanks for clarifying! Okay cool, let me see what I can come up with.

First I think I would define your categorical columns as factors in the original df, since that will cause `compose_data` to autogenerate the `n_plot` and `n_site` columns:

```r
df <- data.frame(
  plot = factor(rep(1:10, times = 2)),
  site = factor(rep(1:5, each = 2, times = 2))
)
```

`tidybayes` doesn't have something to do nesting directly, but you could use the `expand` function from `tidyr` to do it. I'll suggest loading these packages:

```r
library(dplyr)
library(tidyr)
library(magrittr)
```

Then you can use `tidyr::expand` to generate a grid that has the nesting structure you want, from which the `site` column would be the `site_id` value you are looking for:

```r
expand(df, nesting(plot, site))
```

```
# A tibble: 10 x 2
     plot   site
   <fctr> <fctr>
 1      1      1
 2      2      1
 3      3      2
 4      4      2
 5      5      3
 6      6      3
 7      7      4
 8      8      4
 9      9      5
10     10      5
```

You could stick this all in one call to compose_data like this:

```r
compose_data(
  df,
  site_id = expand(df, nesting(plot, site))$site
)
```

```
$plot
 [1]  1  2  3  4  5  6  7  8  9 10  1  2  3  4  5  6  7  8  9 10

$n_plot
[1] 10

$site
 [1] 1 1 2 2 3 3 4 4 5 5 1 1 2 2 3 3 4 4 5 5

$n_site
[1] 5

$n
[1] 20

$site_id
 [1] 1 1 2 2 3 3 4 4 5 5

$n_site_id
[1] 5
```

And if you don't want the auto-generated `n_site_id`, and (like me) you are more of a pipe person, you could use `%$%` from magrittr to extract the `site` column and pass it through `as.numeric`:

```r
compose_data(
  df,
  site_id = df %>% expand(nesting(plot, site)) %$% as.numeric(site)
)
```

```
$plot
 [1]  1  2  3  4  5  6  7  8  9 10  1  2  3  4  5  6  7  8  9 10

$n_plot
[1] 10

$site
 [1] 1 1 2 2 3 3 4 4 5 5 1 1 2 2 3 3 4 4 5 5

$n_site
[1] 5

$n
[1] 20

$site_id
 [1] 1 1 2 2 3 3 4 4 5 5
```

I'm not sure I can come up with a simpler solution without writing a more specialized function to handle this case.

Since part of tidybayes involves making these sorts of tedious tasks simpler, the question is: does that syntax feel suitably concise? I'm on the fence, but I am curious what your opinion is. I might think about alternatives or adding a function to do something like this. If I were to do that, I'd probably like to get more examples of these sorts of cases to generalize something from. If you have some more that would help.

**Comment by mjskay** [comment]
As an example, I would consider adding a function like this:

```r
nested_index = function(.data, x, y) {
  .x = enquo(x)
  .y = enquo(y)
  
  .data %<>% select(!!.x, !!.y)
  
  index = 
    .data %>%
    group_by(!!.x) %>%
    slice(1) %>%
    pull(!!.y) %>%
    as.numeric()

  if(nrow(distinct(.data)) != length(index)) {
    stop(paste0(
      "`", quo_text(.x), "` does not appear to be nested in `", quo_text(.y),
      "`: there are multiple values of `", quo_text(.y), "` for at least one value of `", quo_text(.x), "`"
    ))
  }
  
  index
}
```

Which could then be used like this:

```r
df %>%
  compose_data(site_id = nested_index(., plot, site))
```

```
$plot
 [1]  1  2  3  4  5  6  7  8  9 10  1  2  3  4  5  6  7  8  9 10

$n_plot
[1] 10

$site
 [1] 1 1 2 2 3 3 4 4 5 5 1 1 2 2 3 3 4 4 5 5

$n_site
[1] 5

$n
[1] 20

$site_id
 [1] 1 1 2 2 3 3 4 4 5 5
```

But I would rather make sure that I'm not missing some more general usage (e.g. more complex nesting structure that might be turned into a multidimensional array?) before doing something like that.

**Comment by aornugent** [comment]
I like it a lot. The `nested_index` syntax was exactly what I was imagining and it's interesting to see how such a function would be constructed. 

One minor detail is that `site` in the data frame is really only used to construct `site_id` and not needed as data for the model. Perhaps a `remove = TRUE` flag could be added? But carrying it along is a small price for conciseness.

This covers my immediate use case and nothing more complicated springs to mind. The Stan manual has a section on multiple indexing [Chapter 26 in the 2.16 edition] that might be relevant. 

Thanks for the response and support!

**Comment by mjskay** [comment]
Cool. I think what I will probably end up doing is two-fold:

1. Change `compose_data` so that successive arguments are evaluated in an environment that includes the data list as constructed so far. The is the sort of thing that `dplyr::mutate` does so that you can refer to previous columns in the same call to `mutate`.

2. Ensure `compose_data` overwrites old columns with the same name as new ones are written to it.

3. Write a variant of `nested_index` similar to the one above, but which simply takes two vectors (so more like your `nestd` actually, though I think I will add some sanity checks).

This would allow something even simpler than what I wrote before, like this:

```r
df %>%
  compose_data(site_id = nested_index(plot, site))
```

And then if you wanted to drop unused columns, you would be able to do something like this (because of (2)):

```r
df %>%
  compose_data(
    site_id = nested_index(plot, site),
    site = NULL
  )
```

Or I suppose even this, if you were okay with the dual use of the name "site":

```r
df %>%
  compose_data(
    site = nested_index(plot, site)
  )
```

Anyhow, I'll put that on my todo :)

**Comment by mjskay** [comment]
I did mostly what I suggested, with some extra bits to catch some possible errors (particularly if factors have missing levels in them).

I also changed the syntax slightly because the name `nested_index` seemed both too specific and not clear enough on what the argument order should be (is it `nested_index(plot, site)` or `nested_index(site, plot)`?). 

I ended up reversing the argument order and calling the function `x_at_y` (because it gives a vector `k` such that `k[y] == x`; i.e. `k` gives you the `x` at `y`).

It works like this:

```r
df %>%
  compose_data(site = x_at_y(site, plot))
```
```
$plot
 [1]  1  2  3  4  5  6  7  8  9 10  1  2  3  4  5  6  7  8  9 10

$n_plot
[1] 10

$site
 [1] 1 1 2 2 3 3 4 4 5 5

$n_site
[1] 5

$n
[1] 20
```
